name: Relabel PRs
permissions:
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]
  issue_comment: # in GitHub API, all PRs are issues, but not all issues are PRs.
    types: [created]

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  run-check:
    runs-on: ubuntu-latest
    env:
      comment_user: ${{github.event.comment.user.login}}
      issue_user: ${{github.event.issue.user.login}}
      pr_review_user: ${{github.event.pull_request_review_comment.user.login}}
      pr_user: ${{github.event.pull_request.user.login}}
    steps:
      - name: Remove `wait for update` label on push
        uses: actions/github-script@v6
        if: ${{($comment_user == $issue_user && contains(github.event.issue.labels.*.name, 'wait for update')   && !contains(github.event.issue.labels.*.name, 'user responded')) || ( contains(github.event.pull_request.labels.*.name, 'wait for update') &&  $pr_review_user == $pr_user ) || ( contains(github.event.pull_request.labels.*.name, 'wait for update') && !contains(github.event.pull_request.labels.*.name, 'user responded') ) }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["user responded"]
            })
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "wait for update"
            })
